export const bancosData = {
  "metadata": {
    "ultimaActualizacion": "2024-09-24",
    "fuente": "CNBV - Comisión Nacional Bancaria y de Valores",
    "version": "1.0.0",
    "totalBancos": 46
  },
  "bancos": {
    "002": {
      "codigo": "002",
      "nombre": "BANAMEX",
      "nombreCompleto": "Banco Nacional de México S.A.",
      "nombreCorto": "Banamex",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-021-2345",
      "website": "https://www.banamex.com",
      "swift": "BNMXMXMM"
    },
    "006": {
      "codigo": "006",
      "nombre": "BANCOMEXT",
      "nombreCompleto": "Banco Nacional de Comercio Exterior S.N.C.",
      "nombreCorto": "Bancomext",
      "tipo": "Desarrollo",
      "pais": "México",
      "telefono": "800-639-9000",
      "website": "https://www.bancomext.com",
      "swift": "BNEXMXMM"
    },
    "009": {
      "codigo": "009",
      "nombre": "BANOBRAS",
      "nombreCompleto": "Banco Nacional de Obras y Servicios Públicos S.N.C.",
      "nombreCorto": "Banobras",
      "tipo": "Desarrollo",
      "pais": "México",
      "telefono": "800-266-2272",
      "website": "https://www.banobras.gob.mx",
      "swift": "BNOBMXMM"
    },
    "012": {
      "codigo": "012",
      "nombre": "BBVA MEXICO",
      "nombreCompleto": "BBVA México S.A.",
      "nombreCorto": "BBVA",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-226-2282",
      "website": "https://www.bbva.mx",
      "swift": "BCMRMXMM"
    },
    "014": {
      "codigo": "014",
      "nombre": "SANTANDER",
      "nombreCompleto": "Banco Santander México S.A.",
      "nombreCorto": "Santander",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-762-7777",
      "website": "https://www.santander.com.mx",
      "swift": "BMSXMXMM"
    },
    "019": {
      "codigo": "019",
      "nombre": "BANJERCITO",
      "nombreCompleto": "Banco Nacional del Ejército, Fuerza Aérea y Armada S.N.C.",
      "nombreCorto": "Banjercito",
      "tipo": "Desarrollo",
      "pais": "México",
      "telefono": "800-226-5372",
      "website": "https://www.banjercito.com.mx",
      "swift": "BEJEMXMM"
    },
    "021": {
      "codigo": "021",
      "nombre": "HSBC",
      "nombreCompleto": "HSBC México S.A.",
      "nombreCorto": "HSBC",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-472-2472",
      "website": "https://www.hsbc.com.mx",
      "swift": "BIMEMXMM"
    },
    "030": {
      "codigo": "030",
      "nombre": "BAJIO",
      "nombreCompleto": "Banco del Bajío S.A.",
      "nombreCorto": "BanBajío",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-224-4646",
      "website": "https://www.bb.com.mx",
      "swift": "BCBAMXMM"
    },
    "032": {
      "codigo": "032",
      "nombre": "IXE",
      "nombreCompleto": "IXE Banco S.A.",
      "nombreCorto": "IXE",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-463-4932",
      "website": "https://www.ixe.com.mx",
      "swift": "IXEMXMXM"
    },
    "036": {
      "codigo": "036",
      "nombre": "INBURSA",
      "nombreCompleto": "Banco Inbursa S.A.",
      "nombreCorto": "Inbursa",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-464-6287",
      "website": "https://www.inbursa.com",
      "swift": "BCINSXMX"
    },
    "037": {
      "codigo": "037",
      "nombre": "INTERACCIONES",
      "nombreCompleto": "Banco Interacciones S.A.",
      "nombreCorto": "Interacciones",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-002-2828",
      "website": "https://www.bancointeracciones.com",
      "swift": "BINTMXMX"
    },
    "042": {
      "codigo": "042",
      "nombre": "MIFEL",
      "nombreCompleto": "Banca Mifel S.A.",
      "nombreCorto": "Mifel",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-464-3351",
      "website": "https://www.mifel.com.mx",
      "swift": "MIFEMXMX"
    },
    "044": {
      "codigo": "044",
      "nombre": "SCOTIABANK",
      "nombreCompleto": "Scotiabank Inverlat S.A.",
      "nombreCorto": "Scotiabank",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-472-6842",
      "website": "https://www.scotiabank.com.mx",
      "swift": "NOSCMXMX"
    },
    "058": {
      "codigo": "058",
      "nombre": "BANREGIO",
      "nombreCompleto": "Banco Regional de Monterrey S.A.",
      "nombreCorto": "Banregio",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-723-4746",
      "website": "https://www.banregio.com",
      "swift": "BRMNMXMM"
    },
    "059": {
      "codigo": "059",
      "nombre": "INVEX",
      "nombreCompleto": "Banco Invex S.A.",
      "nombreCorto": "Invex",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-468-3900",
      "website": "https://www.invex.com",
      "swift": "INVEMXMM"
    },
    "060": {
      "codigo": "060",
      "nombre": "BANSI",
      "nombreCompleto": "Banco del Centro S.A.",
      "nombreCorto": "Bansi",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-226-7400",
      "website": "https://www.bansi.com.mx",
      "swift": "BCENMXMM"
    },
    "062": {
      "codigo": "062",
      "nombre": "AFIRME",
      "nombreCompleto": "Banca Afirme S.A.",
      "nombreCorto": "Afirme",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-236-4763",
      "website": "https://www.afirme.com",
      "swift": "AFIRMXMX"
    },
    "072": {
      "codigo": "072",
      "nombre": "BANORTE",
      "nombreCompleto": "Banco Mercantil del Norte S.A.",
      "nombreCorto": "Banorte",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-226-6783",
      "website": "https://www.banorte.com",
      "swift": "MENOMXMT"
    },
    "102": {
      "codigo": "102",
      "nombre": "THE ROYAL BANK",
      "nombreCompleto": "The Royal Bank of Scotland México S.A.",
      "nombreCorto": "RBS",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "55-9177-4000",
      "website": "https://www.rbs.com.mx",
      "swift": "RBSSMXMX"
    },
    "103": {
      "codigo": "103",
      "nombre": "AMERICAN EXPRESS",
      "nombreCompleto": "American Express Bank (México) S.A.",
      "nombreCorto": "Amex",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-504-0400",
      "website": "https://www.americanexpress.com.mx",
      "swift": "AEMXMXMX"
    },
    "106": {
      "codigo": "106",
      "nombre": "BANK OF AMERICA",
      "nombreCompleto": "Bank of America México S.A.",
      "nombreCorto": "BofA",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-226-3342",
      "website": "https://www.bankofamerica.com.mx",
      "swift": "BOFAMXMX"
    },
    "108": {
      "codigo": "108",
      "nombre": "MUFG",
      "nombreCompleto": "MUFG Bank México S.A.",
      "nombreCorto": "MUFG",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "55-5249-7000",
      "website": "https://www.mufg.jp",
      "swift": "BOTKMXMX"
    },
    "110": {
      "codigo": "110",
      "nombre": "JP MORGAN",
      "nombreCompleto": "J.P. Morgan Casa de Bolsa S.A. de C.V.",
      "nombreCorto": "JPMorgan",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-570-0800",
      "website": "https://www.jpmorgan.com.mx",
      "swift": "CHASDEFX"
    },
    "112": {
      "codigo": "112",
      "nombre": "VE POR MAS",
      "nombreCompleto": "Banco Ve Por Más S.A.",
      "nombreCorto": "Ve Por Más",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-386-7627",
      "website": "https://www.vepormas.com.mx",
      "swift": "VPORMXMX"
    },
    "113": {
      "codigo": "113",
      "nombre": "CREDIT SUISSE",
      "nombreCompleto": "Credit Suisse México S.A.",
      "nombreCorto": "Credit Suisse",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "55-5282-8500",
      "website": "https://www.credit-suisse.com",
      "swift": "CRESMXMX"
    },
    "116": {
      "codigo": "116",
      "nombre": "AZTECA",
      "nombreCompleto": "Banco Azteca S.A.",
      "nombreCorto": "Azteca",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-040-4000",
      "website": "https://www.bancoazteca.com.mx",
      "swift": "BCAZMXMM"
    },
    "124": {
      "codigo": "124",
      "nombre": "DEUTSCHE",
      "nombreCompleto": "Deutsche Bank México S.A.",
      "nombreCorto": "Deutsche Bank",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "55-5279-8000",
      "website": "https://www.db.com",
      "swift": "DEUTMXMX"
    },
    "126": {
      "codigo": "126",
      "nombre": "CREDIT AGRICOLE",
      "nombreCompleto": "Crédit Agricole Corporate and Investment Bank S.A.",
      "nombreCorto": "Credit Agricole",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "55-9138-8400",
      "website": "https://www.ca-cib.com",
      "swift": "AGRIMXMX"
    },
    "127": {
      "codigo": "127",
      "nombre": "AZTECA",
      "nombreCompleto": "Banco Azteca S.A.",
      "nombreCorto": "Azteca",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-040-4000",
      "website": "https://www.bancoazteca.com.mx",
      "swift": "BCAZMXMM"
    },
    "128": {
      "codigo": "128",
      "nombre": "AUTOFIN",
      "nombreCompleto": "Banco Autofin México S.A.",
      "nombreCorto": "Autofin",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-288-6346",
      "website": "https://www.autofinmexico.com",
      "swift": "AUFIMXMX"
    },
    "129": {
      "codigo": "129",
      "nombre": "BARCLAYS",
      "nombreCompleto": "Barclays Bank México S.A.",
      "nombreCorto": "Barclays",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "55-5279-8600",
      "website": "https://www.barclays.com.mx",
      "swift": "BARCMXMX"
    },
    "130": {
      "codigo": "130",
      "nombre": "COMPARTAMOS",
      "nombreCompleto": "Banco Compartamos S.A.",
      "nombreCorto": "Compartamos",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-266-7272",
      "website": "https://www.compartamos.com.mx",
      "swift": "COMPMXMX"
    },
    "131": {
      "codigo": "131",
      "nombre": "BANCO FAMSA",
      "nombreCompleto": "Banco Famsa S.A.",
      "nombreCorto": "Famsa",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-326-7200",
      "website": "https://www.bancofamsa.com",
      "swift": "FAMSMXMX"
    },
    "132": {
      "codigo": "132",
      "nombre": "BMULTIVA",
      "nombreCompleto": "Banco Multiva S.A.",
      "nombreCorto": "Multiva",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-468-5842",
      "website": "https://www.multiva.com.mx",
      "swift": "MLTIMXMX"
    },
    "133": {
      "codigo": "133",
      "nombre": "ACTINVER",
      "nombreCompleto": "Banco Actinver S.A.",
      "nombreCorto": "Actinver",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-228-4683",
      "website": "https://www.actinver.com",
      "swift": "ACTNMXMX"
    },
    "134": {
      "codigo": "134",
      "nombre": "WAL-MART",
      "nombreCompleto": "Banco Walmart de México Adelante S.A.",
      "nombreCorto": "Walmart",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-925-6278",
      "website": "https://www.bancowalmartmexico.com.mx",
      "swift": "WALMXMMX"
    },
    "135": {
      "codigo": "135",
      "nombre": "NAFIN",
      "nombreCompleto": "Nacional Financiera S.N.C.",
      "nombreCorto": "Nafin",
      "tipo": "Desarrollo",
      "pais": "México",
      "telefono": "800-623-4600",
      "website": "https://www.nafin.com",
      "swift": "NAFINMXM"
    },
    "136": {
      "codigo": "136",
      "nombre": "INTERBANCO",
      "nombreCompleto": "Inter Banco S.A.",
      "nombreCorto": "InterBanco",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-468-3722",
      "website": "https://www.interbanco.com.mx",
      "swift": "INTEMXMX"
    },
    "137": {
      "codigo": "137",
      "nombre": "BANCOPPEL",
      "nombreCompleto": "BanCoppel S.A.",
      "nombreCorto": "Coppel",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-226-7735",
      "website": "https://www.bancoppel.com",
      "swift": "COPPELMX"
    },
    "138": {
      "codigo": "138",
      "nombre": "ABC CAPITAL",
      "nombreCompleto": "ABC Capital S.A.",
      "nombreCorto": "ABC Capital",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "55-9177-7000",
      "website": "https://www.abccapital.com.mx",
      "swift": "ABCAMXMX"
    },
    "139": {
      "codigo": "139",
      "nombre": "UBS BANK",
      "nombreCompleto": "UBS Bank México S.A.",
      "nombreCorto": "UBS",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "55-5279-8700",
      "website": "https://www.ubs.com",
      "swift": "UBSWMXMX"
    },
    "140": {
      "codigo": "140",
      "nombre": "CONSUBANCO",
      "nombreCompleto": "Consubanco S.A.",
      "nombreCorto": "Consubanco",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-266-7822",
      "website": "https://www.consubanco.com",
      "swift": "CNSBMXMX"
    },
    "141": {
      "codigo": "141",
      "nombre": "VOLKSWAGEN",
      "nombreCompleto": "Volkswagen Bank S.A.",
      "nombreCorto": "VW Bank",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-838-9200",
      "website": "https://www.vwfs.com.mx",
      "swift": "VWBAMXMX"
    },
    "143": {
      "codigo": "143",
      "nombre": "CIBANCO",
      "nombreCompleto": "CIBanco S.A.",
      "nombreCorto": "CIBanco",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-242-2626",
      "website": "https://www.cibanco.com",
      "swift": "CIBAMXMX"
    },
    "145": {
      "codigo": "145",
      "nombre": "BBASE",
      "nombreCompleto": "Banco Base S.A.",
      "nombreCorto": "BBase",
      "tipo": "Múltiple",
      "pais": "México",
      "telefono": "800-227-3000",
      "website": "https://www.bancobase.com",
      "swift": "BASEMXMX"
    },
    "166": {
      "codigo": "166",
      "nombre": "BANSEFI",
      "nombreCompleto": "Banco del Ahorro Nacional y Servicios Financieros S.N.C.",
      "nombreCorto": "Bansefi",
      "tipo": "Desarrollo",
      "pais": "México",
      "telefono": "800-726-7334",
      "website": "https://www.bansefi.gob.mx",
      "swift": "BNSEMXMX"
    },
    "168": {
      "codigo": "168",
      "nombre": "HIPOTECARIA FEDERAL",
      "nombreCompleto": "Sociedad Hipotecaria Federal S.N.C.",
      "nombreCorto": "SHF",
      "tipo": "Desarrollo",
      "pais": "México",
      "telefono": "800-466-3342",
      "website": "https://www.shf.gob.mx",
      "swift": "SHFEMXMX"
    },
    "600": {
      "codigo": "600",
      "nombre": "MONEXCB",
      "nombreCompleto": "Monex Casa de Bolsa S.A. de C.V.",
      "nombreCorto": "Monex",
      "tipo": "Casa de Bolsa",
      "pais": "México",
      "telefono": "800-666-3900",
      "website": "https://www.monex.com.mx",
      "swift": "MONXMXMX"
    },
    "601": {
      "codigo": "601",
      "nombre": "GBM",
      "nombreCompleto": "Grupo Bursátil Mexicano Casa de Bolsa S.A. de C.V.",
      "nombreCorto": "GBM",
      "tipo": "Casa de Bolsa",
      "pais": "México",
      "telefono": "800-426-4636",
      "website": "https://www.gbm.com.mx",
      "swift": "GBMXMXMX"
    },
    "602": {
      "codigo": "602",
      "nombre": "MASARI",
      "nombreCompleto": "Masari Casa de Bolsa S.A. de C.V.",
      "nombreCorto": "Masari",
      "tipo": "Casa de Bolsa",
      "pais": "México",
      "telefono": "55-5279-8800",
      "website": "https://www.masari.mx",
      "swift": "MASAMXMX"
    }
  }
};
